version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: css
    destination: /var/www/html/css
  - source: js
    destination: /var/www/html/js
  - source: src
    destination: /var/www/html/src
  - source: /particles.json
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root